server:
  port: 13000

spring:
  application:
    name: Eureka-server13000

eureka:
  instance:
    hostname: eurekaServer13000
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:13001/eureka/,http://127.0.0.1:13002/eureka/

