server:
  port: 14000
spring:
  application:
    name: gateway-server

  #下面是关于Spring Cloud Gateway的配置
  cloud:
    gateway:

#      discovery:
#      # 跨域
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedHeaders: "*"
#            allowedOrigins: "*"
#            allowedMethods:
#            - GET
#              POST
#              DELETE
#              PUT
#              OPTION

      routes:
        - id: oauth2-api
          uri: lb://oauth2-api
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1

        - id: oauth2-auth
          uri: lb://oauth2-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: providerServer1
          uri: lb://provider-server-customer-management   # 客户管理服务
          predicates:
            - Path=/cusManagement/**
          filters:
            - StripPrefix=1

        - id: providerServer2
          uri: lb://provider-server-opportunity-management   # 机会管理服务
          predicates:
            - Path=/oppManagement/**
          filters:
            - StripPrefix=1


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:13000/eureka/, http://127.0.0.1:13001/eureka/, http://127.0.0.1:13002/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
